### ISSUE TITLE
Size of Docker image for uvicorn-gunicorn-fastapi-docker is too large

### ISSUE THREAD

**Issue by rubyfin** [tiangolo/uvicorn-gunicorn-fastapi-docker#15]
FastAPI is great, really nice project, and it is awesome that there is a ready-to-be-used image for it. However, its size is too large for it to be practical - it around 1Gb! Using Alpine image is not ideal, because Alpine distro has incompatibilities with some compiled packages, due to musl lib being used instead of glibc. Sooner or later you always run into issues with Alpine.

Can we have instructions / guide somewhere how to configure uvicorn + gunicorn for fastapi? It would allow anyone to quickly build custom images for FASTApi?

**Comment by laurentS** [comment]
I am not involved in maintaining this image but I imagine it should be possible to rebuild a similar one based on `python:3.7-slim` instead of `python:3.7`.
As I am writing this, I found [this related issue](https://github.com/tiangolo/uvicorn-gunicorn-docker/issues/16) on the repo for the image this one is based on.

**Comment by laurentS** [comment]
I just opened a PR to fix this, you can also pull the image from https://hub.docker.com/r/laurents/uvicorn-gunicorn-fastapi until the PR is merged :)

**Comment by tiangolo** [comment]
Thanks for the discussion here everyone! There's now a slim version that you can use if your dependencies don't require a building step :rocket:
