### ISSUE TITLE
Update version of fastapi

### ISSUE THREAD

**Issue by lauraerinmann** [tiangolo/uvicorn-gunicorn-fastapi-docker#179]
I noticed this image uses a version of fastapi from about a year ago:
`fastapi==0.68.1`
Are there plans to the update the images version of fastapi?  Thank yee.

**Comment by brianoflondon** [comment]
Would love to see this refreshed. I'm using it still!

**Comment by tiangolo** [comment]
Thanks for the feedback and the patience. :sweat_smile: 

I updated it several times, so this was probably solved a while ago.

Now that Uvicorn supports managing workers with `--workers`, including restarting dead ones, there's no need for Gunicorn. That also means that it's much simpler to build a Docker image from scratch now, I updated the docs to explain it.

Because of that, I deprecated this Docker image: https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker#-warning-you-probably-dont-need-this-docker-image
