### ISSUE TITLE
High security findings

### ISSUE THREAD

**Issue by Arrrunan** [tiangolo/uvicorn-gunicorn-fastapi-docker#50]
We're using the `tiangolo/uvicorn-gunicorn-fastapi:python3.8-slim` image and after a image scan we got a report with 2 high findings relating to perl. 

`

featurename | featureversion | vulnerability | namespace | description | link | severity | fixedby
-- | -- | -- | -- | -- | -- | -- | --
perl | 5.28.1-6 | CVE-2020-10878 | debian:10 | Perl  before 5.30.3 has an integer overflow related to mishandling of a  "PL_regkind[OP(n)] == NOTHING" situation. A crafted regular expression  could lead to malformed bytecode with a possibility of instruction  injection. | https://security-tracker.debian.org/tracker/CVE-2020-10878 | High |  
perl | 5.28.1-6 | CVE-2020-10543 | debian:10 | Perl  before 5.30.3 on 32-bit platforms allows a heap-based buffer overflow  because nested regular expression quantifiers have an integer overflow. | https://security-tracker.debian.org/tracker/CVE-2020-10543 | High |  

`

is it possible to upgrade perl to 5.30.3?

**Comment by NotoriousRebel** [comment]
Where in the image is perl used? 🤔. Also, why would you create a Github issue for possible security findings instead of sending an email?

**Comment by gbvanrenswoude** [comment]
@NotoriousRebel 
```sh
docker run --rm -it tiangolo/uvicorn-gunicorn:python3.8-slim which perl
/usr/bin/perl
```

Lots of Docker Images are notoriously vulnerable due to people not caring enough to deliver a clean FS and up-to-date binaries. Personally I think he is setting a good example and I fail to see why reporting this as an issue instead of a mail would be a problem.

**Comment by NotoriousRebel** [comment]
@gbvanrenswoude I wasn't seeing it because I was using the alpine image so thanks for pointing that out apologies about that. Github did add a way for owners to create [security policies](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) for cases like this. There is zero problem reporting the issue; rather, it's the manner in which you report it.

**Comment by Arrrunan** [comment]
Fixed it with the alpine image, thanks! I don't mind doing it via security policy but there isn't one for this repository

**Comment by tiangolo** [comment]
Thanks for the help here @NotoriousRebel ! :clap: :bow: 

The image is based on the official Python image, so it wouldn't be an issue with this image but with the base official Python image. On the other side, Perl is not used for anything, it's there just because it's a common tool to have pre-installed and could be needed while building extensions, etc. But nothing calls or uses it.

Anyway, thanks for reporting back and closing the issue @Arrrunan  :+1:
