### ISSUE TITLE
python3.8 tag isn't up to date with latest

### ISSUE THREAD

**Issue by TimOrme** [tiangolo/uvicorn-gunicorn-fastapi-docker#87]
Python3.8 tag hasn't been updated to latest python version:

```
 % docker run -it tiangolo/uvicorn-gunicorn-fastapi:python3.8 python --version
Python 3.8.2
```

But the latest tag is correct:

```
 % docker run -it tiangolo/uvicorn-gunicorn-fastapi:latest python --version   
Python 3.8.6
```

According to the README, these should be the same however.

**Comment by graue70** [comment]
Related to #53.

**Comment by tiangolo** [comment]
Thanks for the feedback (and the patience). :nerd_face: 

I made the images re-build on schedule a while ago, so this was probably solved at some point.

On the other hand, now that Uvicorn supports managing workers with `--workers`, including restarting dead ones, there's no need for Gunicorn. That also means that it's much simpler to build a Docker image from scratch now, I updated the docs to explain it.

Because of that, I deprecated this Docker image: https://github.com/tiangolo/uvicorn-gunicorn-docker#-warning-you-probably-dont-need-this-docker-image
