### ISSUE TITLE
Request for periodic image rebuilds 

### ISSUE THREAD

**Issue by timothyjlaurent** [tiangolo/uvicorn-gunicorn-fastapi-docker#89]
The latest image is now 5 months old and we are experiencing Prisma scan failures associated with security vulnerabilities.

Could we periodically rebuild this and the upstream image so as to base them off of more current python base images (and hopefully making them less vulnerable)?

**Comment by graue70** [comment]
Related to #53.

**Comment by tiangolo** [comment]
Thanks for the idea and the patience with my response! I added automatic image rebuilding a while ago but didn't check this issue.

And now that Uvicorn supports managing workers with `--workers`, including restarting dead ones, there's no need for Gunicorn. That also means that it's much simpler to build a Docker image from scratch now, I updated the docs to explain it.

Because of that, I deprecated this Docker image: https://github.com/tiangolo/uvicorn-gunicorn-docker#-warning-you-probably-dont-need-this-docker-image
